# Generated by Django 5.2 on 2025-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
