# Generated by Django 5.2 on 2025-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_video_youtube_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='checked_for_arabic_subtitles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='available_subtitle_languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
