# Generated by Django 5.2 on 2025-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_video_checked_for_arabic_subtitles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='checked_for_arabic_subtitles',
            new_name='checked_for_relevant_subtitles',
        ),
        migrations.AddField(
            model_name='video',
            name='frontend',
            field=models.CharField(choices=[('de', '🇩🇪'), ('ar', '🇪🇬')], default='ar', max_length=10),
        ),
    ]
