# Generated by Django 5.2 on 2025-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_rename_checked_for_arabic_subtitles_video_checked_for_relevant_subtitles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='status',
            field=models.CharField(choices=[('needs_review', 'Needs Review'), ('live', 'Live'), ('blacklisted', 'Blacklisted')], default='live', max_length=100),
        ),
    ]
