# Generated by Django 5.2 on 2025-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_tag_video_priority_video_title_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='auto_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
