# Generated by Django 5.2 on 2025-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_video_auto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='auto_tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('from_youtube', 'From YouTube'), ('from_search', 'From Search'), ('manual', 'Manual')], default='from_search', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
