# Generated by Django 5.2 on 2025-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_remove_video_auto_tags_tag_type_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('from_youtube', 'From YouTube'), ('from_search', 'From Search'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=100),
        ),
    ]
