# Generated by Django 5.2 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_alter_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
