# Generated by Django 5.2 on 2025-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_video_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='video_views',
            field=models.IntegerField(default=0),
        ),
    ]
