# Generated by Django 5.2 on 2025-04-15 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_video_video_likes_video_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
