# Generated by Django 5.2 on 2025-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_blacklisted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='only_premium',
        ),
        migrations.AddField(
            model_name='video',
            name='available_subtitle_languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('needs_review', 'Needs Review'), ('shortlisted', 'Shortlisted'), ('longlisted', 'Longlisted'), ('not_relevant', 'Not Relevant'), ('assets_generated', 'Assets Generated'), ('blacklisted', 'Blacklisted')], default='needs_review', max_length=20),
        ),
    ]
