# Generated by Django 5.2 on 2025-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_remove_video_is_blacklisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
