# Generated by Django 5.2 on 2025-04-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_video_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shared.language'),
        ),
    ]
