# Generated by Django 5.2 on 2025-04-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_alter_video_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='meanings',
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField()),
                ('creation_method', models.CharField(max_length=50)),
                ('snippet_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='shared.snippet')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='shared.word')),
            ],
        ),
    ]
