# Generated by Django 5.2 on 2025-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_remove_word_meanings_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
