# Generated by Django 5.2 on 2025-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_snippet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('needs_review', 'Needs Review'), ('shortlisted', 'Shortlisted'), ('longlisted', 'Longlisted'), ('not_relevant', 'Not Relevant'), ('snippets_generated', 'Snippets Generated'), ('snippets_and_translations_generated', 'Snippets and Translations Generated'), ('live', 'Live'), ('blacklisted', 'Blacklisted')], default='needs_review', max_length=100),
        ),
    ]
