# Generated by Django 5.2 on 2025-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_contentwish'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwish',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentwish',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
