# Generated by Django 5.2 on 2025-04-14 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapi', '0002_remove_vocabpractice_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='last_watched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
