# Generated by Django 5.2 on 2025-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapi', '0003_alter_videoprogress_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='perceived_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='snippet_percentage_watched',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
