# Generated by Django 5.2 on 2025-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapi', '0004_videoprogress_perceived_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='last_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
