# Generated by Django 5.2 on 2025-04-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapi', '0006_alter_videoprogress_last_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='last_watched',
            new_name='last_practiced',
        ),
    ]
