# Generated by Django 5.2 on 2025-04-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapi', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='language',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.language'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='video',
        ),
        migrations.AlterField(
            model_name='snippetpractice',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_practices', to='shared.snippet'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='occurs_in_snippets',
        ),
        migrations.RemoveField(
            model_name='word',
            name='videos',
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='shared.video'),
        ),
        migrations.AlterField(
            model_name='vocabpractice',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_practices', to='shared.word'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_identification_code',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='PremiumCode',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
